### ISSUE TITLE
Relative hrefs in mounted web app?

### ISSUE THREAD

**Issue by clintwood** [koajs/mount#20]
My use case is for `koa-mount` is mounting apps like this:

``` javascript
app.use(mount('/api', api));
app.use(mount('/apix', apix));
app.use(mount('/app', app));
app.use(mount('/website', webapp));
```

I found links didn't work in `webapp` even if made relative because they were incorrectly `base`d by the browser, e.g.:

`http://domain.com/website/` serving `index.html` containing
`<link rel="stylesheet" href="css/normalize.css">`
results in a browsers request for
`http://domain.com/css/normalize.css`
and not
`http://domain.com/website/css/normalize.css`

I don't want to hardcode all links in `webapp` with the mount prefix or even hardcode  `<base href="/website/">` so I am using `mountPrefix` (from PR #19) to add `base(href='#{mountPrefix}/')` to `head` in `jade`... which works...

I assumed the browser would have correctly `base`d the relative refs... but meh...
Am I missing something here?

**Comment by matthewmueller** [comment]
Just ran into this. Kinda sucks cause it ruins the abstract a little bit, you'd expect `this.redirect('/')` to be relative to the mounted app path, but can't think of a good way of handling this outside of monkey-patching redirect within mount.

**Comment by clintwood** [comment]
I ended up doing this in koa app module that could potentially be mounted:
```javascript
  var app = koa();
...
  app.use(function* redirect(next) {
    // redirect if prefix is not terminated with '/'
    if (this.originalUrl == this.mountPath && this.mountPath.slice(-1) != '/') {
      debug('redirect: %s -> %s/', this.mountPath, this.mountPath);
      this.status = 301;
      this.redirect(this.mountPath + '/');
    }
    // next
    yield* next;
  });
```
Not sure this is entirely the right way to go...
