### ISSUE TITLE
`this.url` is different under node@0.11.14 than node@0.11.15

### ISSUE THREAD

**Issue by greim** [koajs/mount#28]
The client is sending a request to `/api/identity/login`. I have a koa object mounted under `/api`. Under node@0.11.14 `this.url` was `/identity/login`. Under node@0.11.15 it was `/api/identity/login`.

[edit] Should clarify that the behavior under 0.11.14 is the desired behavior and what I assumed the correct behavior.

**Comment by greim** [comment]
Also, iojs@1.0.3 is behaving the same as node@0.11.14, so the problem seems limited to node@0.11.15.

**Comment by dotnil** [comment]
+1 

bumped into this issue today. same node version.

**Comment by jonathanong** [comment]
v0.11.16 is out now. v0.11.15 is considered a buggy version. please open a new issue if the same problem occurs in v0.11.16. also, PR welcomed :)
