### ISSUE TITLE
mount-next

### ISSUE THREAD

**Issue by ahoyahoy** [koajs/mount#39]
where is koa-mount#next for koajs2?

**Comment by tejasmanohar** [comment]
non-existent. read more [here](https://github.com/koajs/koa/issues/625#issuecomment-166201819). if you still want to use koa 2 atm, see if [koa-convert](https://github.com/gyson/koa-convert) does the trick!

**Comment by coderhaoxin** [comment]
I keep that branch in my own repo https://github.com/coderhaoxin/mount/tree/next-by-promise.

@ahoyahoy , If `koa-convert` does not works for `mount`, I'll send a PR to it.

**Comment by ahoyahoy** [comment]
thanks guys

**Comment by nevercast** [comment]
Thanks @coderhaoxin, would you consider linking to [that](https://github.com/coderhaoxin/mount/tree/next-by-promise) as "Unsupported/Unofficial" from the Readme, along with the mention that the next branch needs to be rewritten to fall in line with the details in https://github.com/koajs/koa/issues/625 ?
