### ISSUE TITLE
next branch??

### ISSUE THREAD

**Issue by nevercast** [koajs/mount#40]
There was a next branch here for Koa^2.0, it's seemingly vanished.

Is an updated version being maintained elsewhere?

**Comment by tejasmanohar** [comment]
use koa-convert

**Comment by tejasmanohar** [comment]
we should probably add this to the readme of koa... way too many questions about it.

**Comment by coderhaoxin** [comment]
> we should probably add this to the readme of koa

@tejasmanohar I'm not sure `koa-convert` works with `koa-mount`. I don't have time to check that util this weekend. If no, will submit a PR :smile:

**Comment by coderhaoxin** [comment]
@tejasmanohar should we mention `koa-convert` in `koa`'s `Readme`?

**Comment by tejasmanohar** [comment]
@coderhaoxin 
>should we mention `koa-convert` in `koa`'s `Readme`?

probably. we've seen soo many issues opened about using modules for koa 2 :P

**Comment by nevercast** [comment]
I am using koa-convert, but last week I didn't have to. There was a #next branch that i was tracking against.

Unless there is another repo out there that has the name koa-mount without being THIS repo.

**Comment by nevercast** [comment]
Searched through all the other issues as mentioned and found my answers. Should have checked closes issues first. Thanks team.

**Comment by vesparny** [comment]
@nevercast how did you manage to have it working with koa-router?

**Comment by coderhaoxin** [comment]
@nevercast I keep the branch in my own forked repo

https://github.com/coderhaoxin/mount/tree/next-by-promise

**Comment by nevercast** [comment]
@vesparny I found a fork that added a next implementation. I might switch to tracking @coderhaoxin 's branch tomorrow when I'm back at work.
