### ISSUE TITLE
Use of async function causes problems in recent versions (but not latest) of node.js

### ISSUE THREAD

**Issue by adailey14** [koajs/mount#55]
When using the latest version of koa-mount I run into a parsing problem with Node.js understanding the async function syntax when importing koa-mount. I updated to the latest version of node which supports async natively and now things are working.

I wouldn't have expected that - would have expected koa-mount to export a transpiled version that would work without native async support.

**Comment by coderhaoxin** [comment]
@adailey14 `koa-mount@3.0.0` needs nodejs@7.6+. You can use `koa-mount@2.0.0`.

**Comment by adailey14** [comment]
Ok thanks, in general is there any way to tell which version of Node an npm package requires?

**Comment by coderhaoxin** [comment]
https://github.com/koajs/mount/blob/master/package.json#L38-L40

**Comment by adailey14** [comment]
Thank you!
