### ISSUE TITLE
[Question] Nested mounting and ctx.mountPrefix

### ISSUE THREAD

**Issue by nervgh** [koajs/mount#56]
Hi all!

First of all, I would like to say "thanks" for this module :+1: 

### Backgound + Problem
My problem is: I cannot make redirecting properly because I use nested mounting.
I think the code snippet might look like this:
```js
const Koa = require('koa')
const mount = require('koa-mount')
const Router = require('koa-trie-router')

let app = new Koa()

let router = new Router() // documents router
router.get('/add', function(ctx) {
  ctx.redirect(ctx.mountPath) // <-- my problem is here
})

let middleware = mount('/documents', router.middleware()) // (1) level

app.use(mount('/admin', middleware)) // (2) level
app.listen()
```
When I start my server and go to `http://localhost/admin/documents/add` page then the server redirects me to `/documents` url which does not exists.  I mean the target url should be `/admin/documents` in my case.
My log looks like this:
```
ctx.path          /admin/documents/add
ctx.mountPath     /documents
ctx.url           /admin/documents/add?foo
ctx.originalUrl   /admin/documents/add?foo
```
And I see what I need something like `ctx.mountPrefix` which would be calculated using next simple way:
```js
let index =  ctx.path.lastIndexOf(ctx.mountPath)
ctx.mountPrefix = ctx.path.slice(0, index)
```
In that case the log will look like this:
```
ctx.path          /admin/documents/add
ctx.mountPrefix   /admin
ctx.mountPath     /documents
ctx.url           /admin/documents/add?foo
ctx.originalUrl   /admin/documents/add?foo
```
And I could be write something like this for solving my problem:
```js
router.get('/add', function(ctx) {
  ctx.redirect(ctx.mountPrefix + ctx.mountPath) // --> /admin/documents
})
```

### Question
What do you think about including `ctx.mountPrefix` in `koa-mount` package?
Is it make sense or not?

#### 1
Why I use nested mounting?
I automated mounting and routing which depends on folder structure using [koa-architect](https://github.com/nervgh/koa-architect).

#### 2
Incorrect redirecting is one part of the problem. Also I have the links in templates which forms same way:
```html
<a href="{{ ctx.mountPrefix }}{{ ctx.mountPath }}/edit/{{ item.id }}">edit</a>
```

**Comment by coderhaoxin** [comment]
> What do you think about including ctx.mountPrefix in koa-mount package ?

IMO, we need `mountPrefix` :)

**Comment by nervgh** [comment]
Does it mean what I need PR this feature? =)

**Comment by coderhaoxin** [comment]
PR welcome :)

cc @jonathanong

**Comment by nervgh** [comment]
I wrote my own middleware that do what I need.
