### ISSUE TITLE
Cannot read property 'middleware' of undefined

### ISSUE THREAD

**Issue by AshwinTayson** [koajs/mount#66]
I'm using the example given. But it doesn't work.

```
const mount = require('koa-mount');
const Koa = require('koa');

const app = new Koa();

async function world(ctx, next) {
  await next();
  ctx.body = 'World';
}

app.use(mount('/public'), world);
```

Versions
"koa": "^2.5.1",
"koa-mount": "^3.0.0",

**Comment by hcz** [comment]
It's not the correct way to use `koa-mount`.
In your example `world` should be a Koa instance with its own routes.

**Comment by mbavio** [comment]
@hcz that's not correct: https://github.com/koajs/mount#mounting-middleware

@AshwinTayson you have an in your code:

`app.use(mount('/public'), world);`

should be:

`app.use(mount('/public', world));

**Comment by hcz** [comment]
@mbavio yes, you're right. Thanks!
