### ISSUE TITLE
Protected path with auth 🚧 -- Question

### ISSUE THREAD

**Issue by macarthuror** [koajs/mount#76]
## Hello everyone 🖖
Is it possible to protect a path in the public directory?
Right now I'm developing a project using sessions for the auth, but I want to protect the resources for the no authenticated people.

### This is my code rigth now

```javascript
app.use(mount('/assets', serve(__dirname + '/../public')))
```
I'm trying to implement a middleware before serve the files but all what I tried failed.

**Does anyone have some idea to solve it ?**
### *Thanks 😊*

**Comment by macarthuror** [comment]
Allrady resolved 👌

To verify I used a global middleware who checks when someone want to get the files.

```javascript
app.use((ctx) => {
  const { path } = ctx
  if (path.includes('/assets/private')) {
    //
    // Do something ...
    //
  } else {
    ctx.throw(401)
    return
  }
})
```

**Comment by dominicegginton** [comment]
Hi @macarthuror 👋🏻 

I believe that writing a custom middleware that checks if the user is authenticated for given recourses. Here is an example of such middleware that accepts an array of paths you would like to protect. This example uses a simple check for a boolean value assigned to the clients cookie using [**koa-session**](https://github.com/koajs/session), you can see how this is set in `routes/authentication.js`.

#### index.js
```js
const authenticationRouter = require('./routes/authentication')
const protect = require('./middleware/protect.')

/* SETUP MIDDLEWARE */
app.use(protect(['/assets/protected.txt']))
app.use(mount('/assets', serve(__dirname + '/../public')))

/* SETUP ROUTERS */
app.use(authenticationRouter.routes())
app.use(authenticationRouter.allowedMethods())
```
> Make sure the **protect** middleware is above the **mount** middleware
#### middleware/protect.js
```js
function protect (protectedPaths) {
  return (ctx, next) => {
    if (!protectedPaths.includes(ctx.path)) return next()
    if (ctx.session.authenticated) return next()
    else ctx.status = 401
  }
}

module.exports = protect
```
#### routes/authentication.js
```js
const Router = require('@koa/router')

const router = new Router()

router.get('/login', async ctx => {
  if (ctx.session.authenticated !== true) await ctx.render('login')
  else ctx.redirect('/')
})

router.post('/login', async ctx => {
  ctx.session.authenticated = true
  ctx.redirect('/')
})

router.get('/logout', async ctx => {
  ctx.session.authenticated = false
  ctx.redirect('/')
})

module.exports = router
```

Hope this helps 😄

**Comment by dominicegginton** [comment]
I didn't see you have found a solution and closed this until I had already commented, nice to see your solution 😄

**Comment by macarthuror** [comment]
Hi @dominicegginton 🖖,

Anyway thanks for your solution, helps me to have other ideas 😁
